# Generated by Django 3.2.7 on 2022-01-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_order_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='gender',
            field=models.CharField(blank=True, choices=[('G', 'Select gender'), ('M', 'Male'), ('F', 'Female')], default='G', max_length=1, null=True),
        ),
    ]
