# Generated by Django 3.2.7 on 2022-01-28 13:13

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_order_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='country',
            field=django_countries.fields.CountryField(default='US', max_length=2),
        ),
    ]
