# Generated by Django 3.2.7 on 2021-12-24 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='paypal_id',
            new_name='stripe_charge_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='owner',
            new_name='user',
        ),
    ]
