# Generated by Django 3.2.7 on 2022-02-07 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_order_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe_charge_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
