# Generated by Django 3.2.7 on 2022-01-01 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_coupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkoutaddress',
            old_name='owner',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='owner',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='orderproduct',
            old_name='owner',
            new_name='user',
        ),
    ]
