# Generated by Django 3.2.7 on 2022-02-08 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_stripe_charge_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ordered_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='start_date',
        ),
    ]
