# Generated by Django 3.2.7 on 2022-01-01 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20220101_0219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='paypal_customer_id',
            new_name='stripe_customer_id',
        ),
    ]
